server:
  servlet:
    context-path: /file
    encoding:
      charset: UTF-8
  port: 8080
spring:
  datasource:
    username: postgres
    password: Pfrjcvjltcfyn1992
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/file-m2
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true

store:
  folder: /store
  zip: files.zip
