version: '3.1'

volumes:
  cloud-postgres_nya: {}

services:
  app:
    container_name: springboot-postgresql
    image: 'docker-spring-boot-postgres:latest'
    build: ./
    ports:
      - 8189:8189
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/nya_db
      - TZ=Europe/Moscow
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres
    container_name: db
    restart: always
    volumes:
      - cloud-postgres_nya:/var/lib/postgresql
    environment:
      POSTGRES_DB: nya_db
      POSTGRES_USER: nya
      POSTGRES_PASSWORD: nya777
      TZ: Europe/Moscow
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 5s
      timeout: 2s
      retries: 2
    ports:
      - 5432:5432