server:
  port: 8189
  servlet:
    context-path: /free
spring:
  datasource:
#    username: nya
#    password: nya777
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5436/nya_db
    username: postgres
    password: Pfrjcvjltcfyn1992
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/nya_base14
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true

pageSize: 5